---
title: "MAT 4376 - Project 2"
author: "Alli Selwah"
output: html_document
---

```{r}
library(readxl)

ab_data <- read_excel("/Users/allisonselwah/Downloads/MAT4376/project2/ab_data.xlsx")

```

```{r}
# library(ggplot2)
# 
# ggplot(data=ab_data, aes(x=Hour, y=landing_encoded)) +
#   geom_bar(stat="identity", width=0.7, fill="steelblue")+
#   theme_minimal()
# 
# ggplot(data=ab_data, aes(x=Day, y=landing_encoded)) +
#   geom_bar(stat="identity", width=0.7, fill="steelblue")+
#   theme_minimal()
# 
# ggplot(data=ab_data, aes(x=Hour, y=group_encoded)) +
#   geom_bar(stat="identity", width=0.7, fill="steelblue")+
#   theme_minimal()
```

```{r}
library(ggplot2)

ggplot(data=ab_data, aes(x=Day, y=converted)) +
   geom_bar(stat="identity", width=0.7, fill="steelblue")+
   theme_minimal()

ggplot(data=ab_data, aes(x=Hour, y=converted)) +
   geom_bar(stat="identity", width=0.7, fill="steelblue")+
   theme_minimal()

ggplot(ab_data, aes(x = Day, y = Hour, color = landing_page)) +
  geom_point()
```