---
title: "Task 3"
author: "Alli Selwah"
output: html_document
---

Start with a subset of 100 data points and perform inference. Find the posterior probability that the new page has a higher conversion rate. Hint: use random samples from the independent posteriors to estimate the probability. Update the posteriors with another 100 data points. At what data size do the priors become irrelevant?

```{r, echo = FALSE}
suppressPackageStartupMessages(library(readxl))

suppressPackageStartupMessages(library(dplyr))

ab_data <- read_excel("/Users/allisonselwah/Downloads/MAT4376/project2/ab_data_v2.xlsx")

source( "BernBeta.R" )

df <- data.frame(ab_data)

df <- subset(df, select = c("landing_page", "landing_encoded", "converted"))

print(paste("PRIOR 1 - BINOMIAL FAVOURING OLD PAGE"))

# Test 1

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(c(2,20), c(rand_df$landing_encoded, rand_df$converted))

# Test 2

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 3

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))
```

```{r, echo=FALSE}
print(paste("PRIOR 2 - UNIFORM DISTRIBUTION"))

# Test 1

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(c(1,1), c(rand_df$landing_encoded, rand_df$converted))

# Test 2

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 3

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 4

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))
```

```{r, echo=FALSE}
print(paste("PRIOR 3 - BINOMIAL FAVOURING NEW PAGE"))

# Test 1

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(c(20,2), c(rand_df$landing_encoded, rand_df$converted))

# Test 2

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 3

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 4

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))

# Test 5

rand_df <- df[sample(nrow(df), size=100), ]

df_table <- table(rand_df$landing_encoded, rand_df$converted)

df_table

conRate <- df_table[1,2] / (df_table[1]+df_table[1,2])

print(paste("Conversion Rate: ", round(conRate*100, 2), "%"))

inf <- BernBeta(inf, c(rand_df$landing_encoded, rand_df$converted))
```